'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { ArrowRightOnRectangleIcon, Bars3Icon, BellIcon, CalendarDaysIcon, ClipboardDocumentCheckIcon, HomeIcon, UserGroupIcon, XMarkIcon } from '@heroicons/react/24/outline';
import { api, user } from '@/lib/api';

export default function Shell({ children }: { children: React.ReactNode }) {
  const [me, setMe] = useState<any>(null); const [count, setCount] = useState(0); const [menuOpen, setMenuOpen] = useState(false); const path = usePathname(); const router = useRouter();
  useEffect(() => { const account = user(); setMe(account); if (!account) { router.push('/login'); return; } api('/notifications').then((items: any[]) => setCount(items.filter(item => !item.is_read).length)).catch(() => {}); const base = process.env.NEXT_PUBLIC_WS_URL; const stored = localStorage.getItem('token'); if (!base || !stored) return; const ws = new WebSocket(`${base}/ws/${account.id}?token=${encodeURIComponent(stored)}`); ws.onmessage = () => setCount(value => value + 1); return () => ws.close(); }, [router]);
  if (!me) return null;
  const instructor = me.role === 'instructor' || me.role === 'admin';
  const navigation: [string, string, any][] = instructor ? [['Instructor dashboard', '/instructor', HomeIcon], ['Availability & lessons', '/instructor#availability', CalendarDaysIcon], ['My bookings', '/bookings', CalendarDaysIcon], ['Feedback reports', '/feedback', ClipboardDocumentCheckIcon], ['Notifications', '/notifications', BellIcon]] : [['Learner dashboard', '/dashboard', HomeIcon], ['Book a lesson', '/dashboard#availability', CalendarDaysIcon], ['My bookings', '/bookings', CalendarDaysIcon], ['My progress', '/feedback', ClipboardDocumentCheckIcon], ['Notifications', '/notifications', BellIcon]];
  const nav = <nav className="space-y-1">{navigation.map(([name, href, Icon]) => <Link onClick={() => setMenuOpen(false)} key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold ${path === href ? 'bg-teal-50 text-teal-800' : 'text-slate-600 hover:bg-slate-50'}`}><Icon className="h-5 w-5"/>{name}{name === 'Notifications' && count > 0 ? <span className="ml-auto badge bg-red-100 text-red-700">{count}</span> : null}</Link>)}</nav>;
  const signOut = () => { localStorage.clear(); router.push('/login'); };
  return <div className="min-h-screen bg-stone-50"><aside className="fixed inset-y-0 left-0 hidden w-72 border-r border-slate-200 bg-white p-5 lg:flex lg:flex-col"><Link href="/" className="px-2 text-2xl font-black tracking-tight">RAJ<span className="text-teal-700">.</span></Link><p className="px-2 pt-1 text-xs font-medium text-slate-500">{instructor ? 'Instructor workspace' : 'Learner workspace'}</p><div className="mt-8">{nav}</div><button onClick={signOut} className="mt-auto flex items-center gap-2 px-2 py-2 text-sm font-semibold text-slate-500"><ArrowRightOnRectangleIcon className="h-5 w-5"/>Sign out</button></aside>{menuOpen && <div className="fixed inset-0 z-50 bg-slate-950/60 lg:hidden"><aside className="h-full w-[86%] max-w-sm bg-white p-5"><div className="flex items-center justify-between"><Link href="/" onClick={() => setMenuOpen(false)} className="text-2xl font-black">RAJ<span className="text-teal-700">.</span></Link><button aria-label="Close navigation" onClick={() => setMenuOpen(false)} className="rounded-lg p-2"><XMarkIcon className="h-6 w-6"/></button></div><div className="mt-8">{nav}</div><button onClick={signOut} className="absolute bottom-8 flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowRightOnRectangleIcon className="h-5 w-5"/>Sign out</button></aside></div>}<main className="lg:pl-72"><header className="sticky top-0 z-30 flex items-center gap-3 border-b border-slate-200 bg-white/95 px-5 py-4 backdrop-blur sm:px-8"><button aria-label="Open navigation" onClick={() => setMenuOpen(true)} className="rounded-lg p-2 lg:hidden"><Bars3Icon className="h-6 w-6"/></button><Link href="/" className="text-xl font-black lg:hidden">RAJ<span className="text-teal-700">.</span></Link><div className="ml-auto flex items-center gap-3"><Link href="/notifications" aria-label="Notifications" className="relative rounded-full p-2 hover:bg-slate-50"><BellIcon className="h-5 w-5"/>{count > 0 && <span className="absolute right-1 top-1 h-2.5 w-2.5 rounded-full bg-red-500"/>}</Link><div className="text-right"><p className="text-sm font-bold">{me.first_name} {me.last_name}</p><p className="text-xs capitalize text-slate-500">{me.role}</p></div></div></header><div className="mx-auto max-w-7xl p-5 sm:p-8">{children}</div></main></div>;
}
