'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRightIcon, Bars3Icon, CheckCircleIcon, XMarkIcon } from '@heroicons/react/24/outline';

const services = [
  ['First lessons', 'Start calm, learn the basics and build confidence at your pace.'],
  ['Restricted prep', 'Practise the skills, routes and decision-making that matter on test day.'],
  ['Full licence coaching', 'Sharpen safe, independent driving habits before your next step.'],
  ['Confidence refreshers', 'Get back behind the wheel with patient coaching and a clear plan.'],
];

export default function Home() {
  const [open, setOpen] = useState(false);
  const links = <><a href="#services" onClick={() => setOpen(false)}>Services</a><a href="#how-it-works" onClick={() => setOpen(false)}>How it works</a><Link onClick={() => setOpen(false)} href="/login">Sign in</Link></>;
  return <main className="overflow-x-hidden bg-stone-50 text-slate-950">
    <header className="absolute inset-x-0 top-0 z-20"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="text-xl font-black tracking-tight text-white">RAJ<span className="text-teal-300">.</span></Link><nav className="hidden items-center gap-8 text-sm font-semibold text-white md:flex">{links}<Link href="/register" className="rounded-full bg-white px-5 py-2.5 text-slate-950">Book a lesson</Link></nav><button aria-label="Open menu" onClick={() => setOpen(true)} className="rounded-lg p-2 text-white md:hidden"><Bars3Icon className="h-6 w-6" /></button></div></header>
    {open && <div className="fixed inset-0 z-50 bg-slate-950/80 p-4 md:hidden"><div className="ml-auto flex min-h-full w-full max-w-sm flex-col rounded-3xl bg-white p-6"><button aria-label="Close menu" onClick={() => setOpen(false)} className="ml-auto rounded-lg p-2"><XMarkIcon className="h-6 w-6" /></button><div className="mt-8 flex flex-col gap-6 text-lg font-bold">{links}<Link href="/register" className="btn btn-primary mt-2">Book a lesson</Link></div></div></div>}
    <section className="landing-grid relative isolate min-h-[720px] overflow-hidden bg-slate-950 text-white"><img src="https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1800&q=85" alt="Learner driver on an Auckland road" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-slate-950 via-slate-950/80 to-slate-950/30"/><div className="mx-auto flex min-h-[720px] max-w-7xl items-end px-5 pb-16 pt-36 sm:px-8 sm:pb-24"><div className="max-w-3xl"><p className="eyebrow text-teal-300">AUCKLAND DRIVING LESSONS</p><h1 className="mt-5 text-5xl font-black leading-[.95] tracking-[-.05em] sm:text-7xl">Drive your way.<br/><span className="text-teal-300">Feel ready.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-200">Clear coaching for your first lesson, restricted test, full licence or a confidence reset. Real skills, no judgement.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="btn btn-primary min-h-12 rounded-full px-6">Find a time <ArrowRightIcon className="ml-2 h-4 w-4" /></Link><a href="#services" className="btn min-h-12 rounded-full border border-white/30 px-6 text-white hover:bg-white/10">Explore services</a></div><p className="mt-7 text-sm text-slate-300">Learner · Restricted · Full licence · Confidence coaching</p></div></div></section>
    <section id="services" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="max-w-2xl"><p className="eyebrow">CHOOSE YOUR STARTING POINT</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Lessons that meet you where you are.</h2></div><div className="mt-12 grid border-t border-slate-300 md:grid-cols-2">{services.map(([title, copy], index) => <article key={title} className="group border-b border-slate-300 py-7 md:px-8 md:even:border-l md:odd:pl-0"><div className="flex items-start justify-between gap-6"><div><p className="text-sm font-bold text-teal-700">0{index + 1}</p><h3 className="mt-3 text-2xl font-bold">{title}</h3><p className="mt-3 max-w-md leading-7 text-slate-600">{copy}</p></div><ArrowRightIcon className="mt-2 h-5 w-5 shrink-0 transition group-hover:translate-x-1"/></div></article>)}</div><Link href="/register" className="btn btn-primary mt-10 rounded-full">Book your lesson <ArrowRightIcon className="ml-2 h-4 w-4"/></Link></section>
    <section id="how-it-works" className="bg-teal-800 px-5 py-20 text-white sm:px-8 sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow text-teal-200">SIMPLE FROM THE START</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Pick a time.<br/>Make progress.</h2></div><ol className="grid gap-7 sm:grid-cols-3">{[['01','Create your learner account'],['02','Choose an instructor and time'],['03','Track feedback after every lesson']].map(([number, text]) => <li key={number} className="border-t border-teal-500 pt-5"><p className="font-mono text-teal-200">{number}</p><p className="mt-5 text-lg font-bold leading-7">{text}</p></li>)}</ol></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid gap-10 rounded-[2rem] bg-white p-7 shadow-sm ring-1 ring-slate-200 md:grid-cols-[1fr_auto] md:items-center md:p-12"><div><p className="eyebrow">DRIVING INSTRUCTOR IN AUCKLAND</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Your next drive can feel different.</h2><p className="mt-4 max-w-xl leading-7 text-slate-600">Book online, get straightforward lesson reminders and keep every progress report in one place.</p><ul className="mt-6 space-y-2 text-sm font-semibold text-slate-700"><li className="flex gap-2"><CheckCircleIcon className="h-5 w-5 text-teal-700"/>Flexible online booking</li><li className="flex gap-2"><CheckCircleIcon className="h-5 w-5 text-teal-700"/>Structured feedback after each lesson</li></ul></div><Link href="/register" className="btn btn-primary min-h-12 rounded-full px-6">Book now <ArrowRightIcon className="ml-2 h-4 w-4"/></Link></div></section>
    <footer className="bg-slate-950 px-5 py-10 text-sm text-slate-300 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 sm:flex-row"><p className="font-black text-white">RAJ<span className="text-teal-300">.</span> INSTRUCTOR</p><p>Driving lessons in Auckland, New Zealand.</p><div className="flex gap-5"><Link href="/login">Sign in</Link><Link href="/register">Learner signup</Link><Link href="/register/instructor">Instructor signup</Link></div></div></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'LocalBusiness', name: 'Raj Instructor', description: 'Driving lessons and licence coaching in Auckland, New Zealand.', areaServed: { '@type': 'City', name: 'Auckland' }, serviceType: ['Driving lessons', 'Restricted licence preparation', 'Full licence coaching'], address: { '@type': 'PostalAddress', addressLocality: 'Auckland', addressCountry: 'NZ' } })}} />
  </main>;
}
