'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { api } from '@/lib/api';

export default function InstructorRegister() {
  const router = useRouter();
  const [form, setForm] = useState({ first_name: '', last_name: '', email: '', phone: '', password: '', bio: '', teaching_areas: '', vehicle: '', licence_number: '', languages: 'English' });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const change = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm({ ...form, [key]: event.target.value });
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const result = await api('/auth/register/instructor', { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('token', result.access_token); localStorage.setItem('user', JSON.stringify(result.user)); router.push('/instructor'); } catch (err: any) { setError(err.message); } finally { setSaving(false); } }
  return <main className="min-h-screen bg-stone-50 px-5 py-10 sm:px-8"><div className="mx-auto max-w-2xl"><Link href="/" className="text-xl font-black">RAJ<span className="text-teal-700">.</span></Link><section className="mt-10 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-10"><p className="eyebrow">INSTRUCTOR ACCOUNT</p><h1 className="mt-2 text-3xl font-black tracking-tight">Start teaching with Raj.</h1><p className="mt-3 leading-7 text-slate-600">Create your instructor profile, then add availability for learners to book.</p>{error && <div role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<form onSubmit={submit} className="mt-8 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">First name<input required className="input mt-2" value={form.first_name} onChange={change('first_name')}/></label><label className="text-sm font-bold">Last name<input required className="input mt-2" value={form.last_name} onChange={change('last_name')}/></label><label className="text-sm font-bold sm:col-span-2">Email<input required type="email" className="input mt-2" value={form.email} onChange={change('email')}/></label><label className="text-sm font-bold">Phone<input className="input mt-2" value={form.phone} onChange={change('phone')}/></label><label className="text-sm font-bold">Instructor licence number <span className="font-normal text-slate-500">optional</span><input className="input mt-2" value={form.licence_number} onChange={change('licence_number')}/></label><label className="text-sm font-bold sm:col-span-2">Password<input required minLength={8} type="password" className="input mt-2" value={form.password} onChange={change('password')}/></label><label className="text-sm font-bold sm:col-span-2">About your teaching style<textarea required minLength={20} className="input mt-2 min-h-28" value={form.bio} onChange={change('bio')}/></label><label className="text-sm font-bold">Teaching areas<input required className="input mt-2" placeholder="e.g. Auckland Central" value={form.teaching_areas} onChange={change('teaching_areas')}/></label><label className="text-sm font-bold">Training vehicle<input required className="input mt-2" placeholder="e.g. Automatic dual-control" value={form.vehicle} onChange={change('vehicle')}/></label><label className="text-sm font-bold sm:col-span-2">Languages<input className="input mt-2" value={form.languages} onChange={change('languages')}/></label><button disabled={saving} className="btn btn-primary min-h-12 sm:col-span-2 disabled:opacity-50">{saving ? 'Creating account…' : 'Create instructor account'}</button></form><p className="mt-6 text-sm text-slate-600">Looking to book lessons? <Link href="/register" className="font-bold text-teal-700">Create a learner account</Link></p></section></div></main>;
}
