"""Initial Raj Instructor schema."""
from alembic import op
import sqlalchemy as sa

revision = "20260814_0001"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sa.String(255), nullable=False), sa.Column("hashed_password", sa.String(255), nullable=False), sa.Column("first_name", sa.String(100), nullable=False), sa.Column("last_name", sa.String(100), nullable=False), sa.Column("role", sa.String(20), nullable=False, server_default="student"), sa.Column("phone", sa.String(50)), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table("instructor_profiles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("bio", sa.Text(), nullable=False), sa.Column("expertise", sa.Text(), nullable=False), sa.Column("services", sa.Text(), nullable=False), sa.Column("vehicle", sa.String(120), nullable=False), sa.Column("teaching_areas", sa.String(255), nullable=False), sa.Column("languages", sa.String(255), nullable=False), sa.Column("image_url", sa.String(500), nullable=False), sa.Column("lesson_price_cents", sa.Integer(), nullable=False), sa.Column("licence_number", sa.String(100)), sa.Column("is_accepting_bookings", sa.Boolean(), nullable=False, server_default=sa.true()), sa.UniqueConstraint("user_id"))
    op.create_table("availability", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("instructor_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("starts_at", sa.DateTime(), nullable=False), sa.Column("ends_at", sa.DateTime(), nullable=False), sa.Column("is_booked", sa.Boolean(), nullable=False, server_default=sa.false()), sa.UniqueConstraint("instructor_id", "starts_at", name="uq_instructor_slot"))
    op.create_index("ix_availability_starts_at", "availability", ["starts_at"])
    op.create_table("bookings", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("student_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("instructor_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("availability_id", sa.Integer(), sa.ForeignKey("availability.id"), nullable=False, unique=True), sa.Column("status", sa.String(30), nullable=False, server_default="pending_payment"), sa.Column("payment_status", sa.String(30), nullable=False, server_default="unpaid"), sa.Column("stripe_session_id", sa.String(255)), sa.Column("payment_reference", sa.String(255)), sa.Column("payment_expires_at", sa.DateTime()), sa.Column("amount_cents", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_bookings_student_id", "bookings", ["student_id"]); op.create_index("ix_bookings_instructor_id", "bookings", ["instructor_id"])
    op.create_table("feedback", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("booking_id", sa.Integer(), sa.ForeignKey("bookings.id"), nullable=False, unique=True), sa.Column("student_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("instructor_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("lesson_summary", sa.Text(), nullable=False), sa.Column("agreed_practice", sa.Text(), nullable=False), sa.Column("further_notes", sa.Text(), nullable=False), sa.Column("metrics_json", sa.Text(), nullable=False), sa.Column("submitted_at", sa.DateTime(), nullable=False))
    op.create_index("ix_feedback_student_id", "feedback", ["student_id"]); op.create_index("ix_feedback_instructor_id", "feedback", ["instructor_id"])
    op.create_table("notifications", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("body", sa.Text(), nullable=False), sa.Column("link", sa.String(500), nullable=False), sa.Column("is_read", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"])
    op.create_table("payment_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("provider_event_id", sa.String(255), nullable=False), sa.Column("event_type", sa.String(120), nullable=False), sa.Column("received_at", sa.DateTime(), nullable=False)); op.create_index("ix_payment_events_provider_event_id", "payment_events", ["provider_event_id"], unique=True)
    op.create_table("deliveries", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("booking_id", sa.Integer(), sa.ForeignKey("bookings.id")), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("kind", sa.String(100), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("booking_id", "user_id", "kind", name="uq_delivery_once")); op.create_index("ix_deliveries_booking_id", "deliveries", ["booking_id"]); op.create_index("ix_deliveries_user_id", "deliveries", ["user_id"])

def downgrade():
    op.drop_table("deliveries"); op.drop_table("payment_events"); op.drop_table("notifications"); op.drop_table("feedback"); op.drop_table("bookings"); op.drop_table("availability"); op.drop_table("instructor_profiles"); op.drop_table("users")
